language: java
jdk:
   -openjdk8


addons:
  sonarcloud:
    organization: "ei-em"
    token:
     secure: "9bd2dd36e2d458f0c6061790b48a42510f91f016" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
