dist: trusty
language: java
jdk:
   -openjdk13
addons:
  apt:
    packages:
        - ant
script: ant build

addons:
  sonarcloud:
    organization: "ei-em"
    token:
     secure: "b63daae4ba4e2b51ae356a37842ff1f3c3d68dfc" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner


